<<<<<<< HEAD
function GwtBootstrap3Demo(){var O='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',hb='"><\/script>',Y='#',Rb='.cache.html',$='/',kb='//',Qb=':',ob='::',oc='<script defer="defer">GwtBootstrap3Demo.onInjectionDone(\'GwtBootstrap3Demo\')<\/script>',gb='<script id="',cc='<script language="javascript" src="',rb='=',Z='?',tb='Bad handler "',ac='DOMContentLoaded',Pb="GWT module 'GwtBootstrap3Demo' may need to be (re)compiled",P='GwtBootstrap3Demo',db='GwtBootstrap3Demo.nocache.js',nb='GwtBootstrap3Demo::',ib='SCRIPT',fb='__gwt_marker_GwtBootstrap3Demo',jb='base',bb='baseUrl',S='begin',R='bootstrap',ab='clear.cache.gif',qb='content',Zb='css/bootstrap-datetimepicker.min.css',Sb='css/bootstrap.min.css',$b='css/demo.css',Yb='css/font-awesome.min.css',_b='css/prettify.css',X='end',Jb='gecko',Kb='gecko1_8',T='gwt.codesvr=',U='gwt.hosted=',V='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Xb='head',Nb='hosted.html?GwtBootstrap3Demo',Wb='href',Ib='ie6',Hb='ie8',Gb='ie9',xb='iframe',_='img',yb="javascript:''",kc='js/bootbox.min.js',lc='js/bootbox.min.js"><\/script>',ic='js/bootstrap-datetimepicker.min.js',jc='js/bootstrap-datetimepicker.min.js"><\/script>',ec='js/bootstrap.min.js',fc='js/bootstrap.min.js"><\/script>',bc='js/jquery-1.10.2.min.js',dc='js/jquery-1.10.2.min.js"><\/script>',gc='js/moment.min.js',hc='js/moment.min.js"><\/script>',mc='js/prettify.js',nc='js/prettify.js"><\/script>',Tb='link',Mb='loadExternalRefs',lb='meta',Ab='moduleRequested',W='moduleStartup',Fb='msie',mb='name',Cb='opera',zb='position:absolute;width:0;height:0;border:none',Ub='rel',Eb='safari',cb='script',Ob='selectingPermutation',Q='startup',Vb='stylesheet',eb='undefined',Lb='unknown',Bb='user.agent',Db='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=O,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:S});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(T)!=-1||(c.indexOf(U)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(V)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(P);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return G(a)}}GwtBootstrap3Demo=null;c.gwtOnLoad(z,P,t,y);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:X})}}
function D(){function e(a){var b=a.lastIndexOf(Y);if(b==-1){b=a.length}var c=a.indexOf(Z);if(c==-1){c=a.length}var d=a.lastIndexOf($,Math.min(c,b));return d>=0?a.substring(0,d+1):O}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(_);b.src=a+ab;a=e(b.src)}return a}
function g(){var a=F(bb);if(a!=null){return a}return O}
function h(){var a=n.getElementsByTagName(cb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(db)!=-1){return e(a[b].src)}}return O}
function i(){var a;if(typeof isBodyLoaded==eb||!isBodyLoaded()){var b=fb;var c;n.write(gb+b+hb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=ib){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return O}
function j(){var a=n.getElementsByTagName(jb);if(a.length>0){return a[a.length-1].href}return O}
function k(){var a=n.location;return a.href==a.protocol+kb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==O){l=h()}if(l==O){l=i()}if(l==O){l=j()}if(l==O&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,O);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=O}u[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{A=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var H;function I(){if(!H){H=true;var a=n.createElement(xb);a.src=yb;a.id=P;a.style.cssText=zb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:W,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(t+K)}}
w[Bb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Cb)!=-1}())return Cb;if(function(){return b.indexOf(Db)!=-1}())return Eb;if(function(){return b.indexOf(Fb)!=-1&&n.documentMode>=9}())return Gb;if(function(){return b.indexOf(Fb)!=-1&&n.documentMode>=8}())return Hb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Ib;if(function(){return b.indexOf(Jb)!=-1}())return Kb;return Lb};v[Bb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};GwtBootstrap3Demo.onScriptLoad=function(){if(H){r=true;C()}};GwtBootstrap3Demo.onInjectionDone=function(){q=true;o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:Mb,millis:(new Date).getTime(),type:X});C()};E();D();var J;var K;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(P))){m.location.reload();return}K=Nb;J=O}o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:Ob});if(!B()){try{alert(Pb);return;var L=J.indexOf(Qb);if(L!=-1){y=Number(J.substring(L+1));J=J.substring(0,L)}K=J+Rb}catch(a){return}}var M;function N(){if(!s){s=true;if(!__gwt_stylesLoaded[Sb]){var a=n.createElement(Tb);__gwt_stylesLoaded[Sb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+Sb);n.getElementsByTagName(Xb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Yb]){var a=n.createElement(Tb);__gwt_stylesLoaded[Yb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+Yb);n.getElementsByTagName(Xb)[0].appendChild(a)}if(!__gwt_stylesLoaded[Zb]){var a=n.createElement(Tb);__gwt_stylesLoaded[Zb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+Zb);n.getElementsByTagName(Xb)[0].appendChild(a)}if(!__gwt_stylesLoaded[$b]){var a=n.createElement(Tb);__gwt_stylesLoaded[$b]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+$b);n.getElementsByTagName(Xb)[0].appendChild(a)}if(!__gwt_stylesLoaded[_b]){var a=n.createElement(Tb);__gwt_stylesLoaded[_b]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+_b);n.getElementsByTagName(Xb)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(ac,N,false)}if(M){clearInterval(M)}}}
if(n.addEventListener){n.addEventListener(ac,function(){I();N()},false)}var M=setInterval(function(){if(/loaded|complete/.test(n.readyState)){I();N()}},50);o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:R,millis:(new Date).getTime(),type:X});o&&o({moduleName:P,sessionId:p,subSystem:Q,evtGroup:Mb,millis:(new Date).getTime(),type:S});if(!__gwt_scriptsLoaded[bc]){__gwt_scriptsLoaded[bc]=true;document.write(cc+t+dc)}if(!__gwt_scriptsLoaded[ec]){__gwt_scriptsLoaded[ec]=true;document.write(cc+t+fc)}if(!__gwt_scriptsLoaded[gc]){__gwt_scriptsLoaded[gc]=true;document.write(cc+t+hc)}if(!__gwt_scriptsLoaded[ic]){__gwt_scriptsLoaded[ic]=true;document.write(cc+t+jc)}if(!__gwt_scriptsLoaded[kc]){__gwt_scriptsLoaded[kc]=true;document.write(cc+t+lc)}if(!__gwt_scriptsLoaded[mc]){__gwt_scriptsLoaded[mc]=true;document.write(cc+t+nc)}n.write(oc)}
=======
function GwtBootstrap3Demo(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Xb='.cache.html',_='/',lb='//',Qb='5CCC497D093258F8B862D348EE7F3B3A',Rb='60ED2920E18714302F580FA5B1B075F0',Sb='9480A2CCF6BC06976E5D43244ACCDF4B',Wb=':',pb='::',sc='<script defer="defer">GwtBootstrap3Demo.onInjectionDone(\'GwtBootstrap3Demo\')<\/script>',hb='<script id="',ic='<script language="javascript" src="',sb='=',$='?',Tb='A65C3703F7F09A98E80CD48B58496265',Ub='B92C0C57866F1D50B1B42BD2A790BC7A',ub='Bad handler "',Vb='D98EF0E31AAEE46E908A503D041A0274',gc='DOMContentLoaded',Q='GwtBootstrap3Demo',eb='GwtBootstrap3Demo.nocache.js',ob='GwtBootstrap3Demo::',jb='SCRIPT',gb='__gwt_marker_GwtBootstrap3Demo',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',dc='css/bootstrap-datetimepicker.min.css',Yb='css/bootstrap.min.css',ec='css/demo.css',cc='css/font-awesome.min.css',fc='css/prettify.css',Y='end',Kb='gecko',Lb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',bc='head',Ob='hosted.html?GwtBootstrap3Demo',ac='href',Jb='ie6',Ib='ie8',Hb='ie9',yb='iframe',ab='img',zb="javascript:''",oc='js/bootstrap-datetimepicker.min.js',pc='js/bootstrap-datetimepicker.min.js"><\/script>',kc='js/bootstrap.min.js',lc='js/bootstrap.min.js"><\/script>',hc='js/jquery-1.10.2.min.js',jc='js/jquery-1.10.2.min.js"><\/script>',mc='js/moment.min.js',nc='js/moment.min.js"><\/script>',qc='js/prettify.js',rc='js/prettify.js"><\/script>',Zb='link',Nb='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Gb='msie',nb='name',Db='opera',Ab='position:absolute;width:0;height:0;border:none',$b='rel',Fb='safari',db='script',Pb='selectingPermutation',R='startup',_b='stylesheet',fb='undefined',Mb='unknown',Cb='user.agent',Eb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}GwtBootstrap3Demo=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Db)!=-1}())return Db;if(function(){return b.indexOf(Eb)!=-1}())return Fb;if(function(){return b.indexOf(Gb)!=-1&&n.documentMode>=9}())return Hb;if(function(){return b.indexOf(Gb)!=-1&&n.documentMode>=8}())return Ib;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;return Mb};v[Cb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};GwtBootstrap3Demo.onScriptLoad=function(){if(I){r=true;C()}};GwtBootstrap3Demo.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Nb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Ob;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Pb});if(!B()){try{G([Ib],Qb);G([Jb],Rb);G([Fb],Sb);G([Hb],Tb);G([Lb],Ub);G([Db],Vb);K=x[H(Cb)];var M=K.indexOf(Wb);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Xb}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[Yb]){var a=n.createElement(Zb);__gwt_stylesLoaded[Yb]=a;a.setAttribute($b,_b);a.setAttribute(ac,t+Yb);n.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[cc]){var a=n.createElement(Zb);__gwt_stylesLoaded[cc]=a;a.setAttribute($b,_b);a.setAttribute(ac,t+cc);n.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[dc]){var a=n.createElement(Zb);__gwt_stylesLoaded[dc]=a;a.setAttribute($b,_b);a.setAttribute(ac,t+dc);n.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[ec]){var a=n.createElement(Zb);__gwt_stylesLoaded[ec]=a;a.setAttribute($b,_b);a.setAttribute(ac,t+ec);n.getElementsByTagName(bc)[0].appendChild(a)}if(!__gwt_stylesLoaded[fc]){var a=n.createElement(Zb);__gwt_stylesLoaded[fc]=a;a.setAttribute($b,_b);a.setAttribute(ac,t+fc);n.getElementsByTagName(bc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(gc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(gc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Nb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[hc]){__gwt_scriptsLoaded[hc]=true;document.write(ic+t+jc)}if(!__gwt_scriptsLoaded[kc]){__gwt_scriptsLoaded[kc]=true;document.write(ic+t+lc)}if(!__gwt_scriptsLoaded[mc]){__gwt_scriptsLoaded[mc]=true;document.write(ic+t+nc)}if(!__gwt_scriptsLoaded[oc]){__gwt_scriptsLoaded[oc]=true;document.write(ic+t+pc)}if(!__gwt_scriptsLoaded[qc]){__gwt_scriptsLoaded[qc]=true;document.write(ic+t+rc)}n.write(sc)}
>>>>>>> f17dbc2ed71ef3914acb6c30c901470e6b6dafbc
GwtBootstrap3Demo();